### ISSUE TITLE
Incorrect detection of Google PageSpeed Insights bot

### ISSUE THREAD

**Issue by alexanevsky** [matomo-org/device-detector#6446] opened 2020-11-25 08:39 UTC
Google [PageSpeed Insights bot](https://developers.google.com/speed/pagespeed/insights/) has 2 user agents:

- Desktop bot: 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Safari/537.36 Chrome-Lighthouse`
- Mobile bot: 
`Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Mobile Safari/537.36 Chrome-Lighthouse`

The method "isMobile" returns _false_ for the mobile bot, but for the PageSpeed service to function properly, it must return _true_.

**Comment by sanchezzzhak** [comment] 2020-11-27 14:19
It's not a mistake, alex.
all these methods
https://github.com/matomo-org/device-detector/blob/308500ea5313706156816f80c69bb73004dd0bd3/DeviceDetector.php#L37-L58
used for real devices, not for the bots

**Comment by sgiehl** [comment] 2020-11-27 14:24
Guess that's actually a duplicate of #5364

**Closed by sgiehl** 2020-11-27 14:24 UTC
