### ISSUE TITLE
Invalid dependencies in 3.11.x branch

### ISSUE THREAD

**Issue by kAlvaro** [matomo-org/device-detector#6304] opened 2020-06-03 09:48 UTC
The 3.11.8 release is declared to [support PHP/5.3.2](https://github.com/matomo-org/device-detector/blob/3.11.8/composer.json#L25) but the **mustangostang/spyc** library introduced [undeclared PHP/5.4 syntax](https://github.com/mustangostang/spyc/issues/86). As a result, Composer offers to install that version and breaks apps running on PHP/5.3.

Not sure of what approach to take. Perhaps you can link to an earlier version. Also, bumping PHP requirement to 5.4 is better that getting syntax errors.

Disclaimer: I fully understand PHP/5.3 is ancient and should be dead by now.

**Comment by sgiehl** [comment] 2020-06-03 13:01
I'm tempted to simply increase our requirement to PHP 5.4 then. PHP 5.3 shouldn't be used much anymore. And with release of version 4 we will drop support for PHP 5 completely.

**Comment by kAlvaro** [comment] 2020-06-03 15:42
The error in the library was introduced in [0.6.3](https://github.com/mustangostang/spyc/commit/b066393167c8701d1b11a3828dd08a550b3d9fa1). [0.6.2](https://github.com/mustangostang/spyc/tree/0.6.2) looks clean. If you aren't using the new feature (*Added feature to convert {} into empty object using stdClass()*, whatever that means) I you can fix the dependency to that version.

**Comment by Findus23** [comment] 2020-06-03 17:38
@sgiehl The PHP requirement is already 5.5 since https://github.com/matomo-org/device-detector/pull/5994

@kAlvaro Keep in mind that 3.11.8 is an old release and not maintained anymore. Also device dector doesn't really depend on mustangostang/spyc as you can use any YAML parsing library you like.

**Comment by kAlvaro** [comment] 2020-06-04 17:23
That's right, this issue only affects the old 3.11.x branch. For what it's worth, Universal Device Detection does not seem to have any problem with the previous version of the YAML parser and Composer will use that version if users declare it as direct dependency, as in:

```
{
 "config": {
    "platform": {
      "php": "5.3.3"
    }
  },
  "require": {
    "piwik/device-detector": "^3.11",
    "mustangostang/spyc": "0.6.2"
  }
}
```
So we have a workaround 🙂

In my humble understanding, the proper fix would be to use version ranges for library dependencies instead of `"*"` (which I think it's a good practice anyway because it prevents errors like this), set it to `0.6.2` or lower (I'm not familiar with either packages so I can't suggest a bottom value) and tag for a maintenance release. However, I understand we can't expect forever fixes so feel free to close as wontfix if you see fit.

**Comment by sgiehl** [comment] 2020-06-16 12:04
Will close this as won't fix. The problem isn't actually on our side. A library we are using with composer released a broken version and that's nothing we can omit. Defining fixed versions might cause other problems when using this library in other composer packages that require other versions...

**Closed by sgiehl** 2020-06-16 12:04 UTC
